### ISSUE TITLE
ROS module documentation header

### ISSUE THREAD

**Issue by gywn9081** [MUsurf/JellyRos2#4]
I think it is best if we go with a header as follows for our python files that will be in ROS.
![image](https://github.com/user-attachments/assets/68188ebd-3df3-4d51-b6b5-c2e39adf616f)
This would explicitly leave out the maintainer and or author tag but I believe this may be a better fit in the package XML.

I have opened this as an issue because I believe whatever the consensus it will be useful to reference this in the future.

**Comment by Spidious** [comment]
denied
